"""init

Revision ID: be5d2fa483ce
Revises: 
Create Date: 2024-09-21 14:15:34.652076

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "be5d2fa483ce"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "receipts",
        sa.Column("id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("total", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "payment_type", sa.Enum("CASH", "CARD", name="paymenttype"), nullable=False
        ),
        sa.Column("payment_amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("rest", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "receipt_products",
        sa.Column("id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("receipt_id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("total", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["receipt_id"], ["receipts.id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("receipt_products")
    op.drop_table("receipts")
    op.drop_table("users")
    # ### end Alembic commands ###
